config/routes.rb
PlaylisterRails::Application.routes.draw do
  root :to => "welcome#index"

  resources :songs

  resources :genres

  resources :artists

end

app/models/song.rb
require 'oembed'
class Song < ActiveRecord::Base
  attr_accessible :artist_id, :genre_id, :name

  # expects an artist object
  def add_artist(artist)
    self.artist_id = artist.id
  end

  # expects a string
  def artist_name=(artist_name)
    artist = Artist.find_by_name(artist_name) || Artist.create(name: artist_name)
    add_artist(artist)
  end

  # expects a genre object
  def add_genre(genre)
    self.genre_id = genre.id
  end

  # expects a string
  def genre_name=(genre_name)
    genre =  Genre.find_by_name(genre_name) || Genre.create(name: genre_name)
    add_genre(genre)
  end

  def artist
    if self.artist_id.nil?
      Artist.new
    else
      Artist.find(self.artist_id)
    end
  end

  def genre
    if self.genre_id.nil?
      Genre.new
    else
      Genre.find(self.genre_id)
    end
  end

  # why are these two methods here?
  # rails expected them because I used the
  # phrase "genre_name" in my new song form
  # hrm...
  def artist_name
    self.artist.name
  end
  def genre_name
    self.genre.name
  end

  def youtube_url
    id = YoutubeSearch.search("#{self.artist.name} - #{self.name}").first["video_id"]
    url = "http://www.youtube.com/watch?v=#{id}"
  end

  def embedcode
    OEmbed::Providers::Youtube.get(self.youtube_url).html
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    @artist = @song.artist
    @genre = @song.genre

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    #raise params.inspect
    #@song = Song.new(params[:song])
    @song = Song.new
    @song.name = params[:song][:name]

    @song.genre_name  = params[:song][:genre_name]
    @song.artist_name = params[:song][:artist_name]

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre_name %><br />
    <%= f.text_field :genre_name %>
  </div>
  <div class="field">
    <%= f.label :artist_name %><br />
    <%= f.text_field :artist_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Genre</th>
    <th>Artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= Genre.find(song.genre_id).name %></td>
    <td><%= Artist.find(song.artist_id).name %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= raw @song.embedcode %>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Genre:</b>
  <%= link_to @genre.name, @genre %>
</p>

<p>
  <b>Artist:</b>
  <%= link_to @artist.name, @artist %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>